# Keto No-Fry Buffalo Cauliflower {#intro}

Ever had the incredible Buffalo Cauliflower from Erewhon? If you haven’t, you MUST! They are probably the first thing that is sold out everytime we shop...THEREFORE I decided to make our own...without the deep fryer! They also use rice flour (which is da bomb) but for a more keto friendly recipe simply replace with almond flour ;)

So here you have it- a simple guide to making Vegan, Gluten-free, Keto, No-Fry Buffalo Cauliflower. Pals and I just so happen to love these on a rainy days here in LA! 

_This way to yum…_

__**Time**__: 35 Mins. __**Yields**__: Roughly two cups

__**Ingredients:**__

* ½ head of Cauliflower
  * 1 egg
  * ½ cup Buffalo sauce (my favorite, “Red Wings”) 
  * ½ stick of butter (substitute vegan butter, my favorite “Miyoko's”)
  * 1 cup almond flour 
  * ½ tsp garlic salt

__**Steps:**__

__For Cauliflower:__

  1. Preheat oven to 450 degrees
  2. Wash and break cauliflower into pieces, let air dry 
  3. Beat egg with a fork or whisk
  4. Toss the cauliflower pieces into egg 
  5. Top with Almond flour and garlic salt (we like to use a Ziplock bag to toss dry ingredients thoroughly).  
  6. Lay on sheet pan with pan liners or foil with a cooking spray. Nothing touching to cook evenly
  7. Bake for 25 minutes or until golden
  
__For sauce:__

  1. Melt butter/vegan butter 
  2. Add in buffalo sauce
  3. Whisk or stir thoroughly
  4. Pour on top of golden cauliflower.
  5. Serve with hemp-ranch dipping sauce (click here for recipe) 


Lol, even the boy said these were _ahhhhmazing!_ 


**Besos & Besos!  -Cassarivera**


```{r, include=FALSE}
#You can label chapter and section titles using `{#label}` after them, e.g., we can reference Chapter \@ref(intro). If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \@ref(methods).

#Figures and tables with captions will be placed in `figure` and `table` environments, respectively.
```

